#! /bin/bash
source /users/onl/.topology

delta=$1
runlength=$2
static=$3
debug=$4

echo "delta=" $delta " runlength=" $runlength $static $debug

root=473/lab5
numRtrs=9

host[1]=$h6x1
host[2]=$h2x4
host[3]=$h2x5
host[4]=$h3x2
host[5]=$h2x3
host[6]=$h5x2
host[7]=$h4x2
host[8]=$h7x1
host[9]=$h1x1

i=1
while [ $i -le ${numRtrs} ] ; do
	ssh ${host[$i]} "cd $root; java TestRouter net2/r${i} \
	    ${delta} ${runlength} ${static} ${debug} >net2/log${i}" &
	i=$((i+1))
done
sleep $((runlength+10))

i=1
while [ $i -le ${numRtrs} ] ; do
	echo "*********** log " $i " *************"
	grep -A50 "Final Report" log${i}
	i=$((i+1))
done
